### ISSUE TITLE
Identifiants auteurs associés à l'article

### ISSUE THREAD

**Issue by brrd** [chapitreneuf/nova#28]
Après la description auteur dans l'article, il faut ajouter une section nommée "Ressources de l’auteur dans d’autres bases" (même police que le reste du texte mais en gras) avec, pour chaque élément de type `<idno type="XXX">YYY</idno>` l'affichage d'un logo cliquable qui renvoie à la page de l'auteur sur une autre plateforme.

Prendre exemple sur Persée, intitulé « Ses notices bibliographiques ailleurs sur la toile » : https://www.persee.fr/authority/231711.

Les identifiants à prendre en charge sont les suivants :

![Identifiants_XML](https://user-images.githubusercontent.com/7335302/67668360-183fd280-f970-11e9-99b3-80653039c72a.PNG)

Avec la composition suivante :

* IdRef : `https://www.idref.fr/identifiant`
* Orcid : `http://orcid.org/identifiant`
* HAL : `https://cv.archives-ouvertes.fr/identifiant`
* ISNI : `http://www.isni.org/identifiant`
* Bnf : `https://data.bnf.fr/fr/identifiant`

Remarques :

* La plupart des auteurs n'ont qu'une partie des identifiants mentionnés. Il ne faudra afficher les icônes que quand elles permettent d'afficher un lien.
* Pour la BNF, les choses sont un peu plus compliquées : 
1) Il existe deux identifiants, l'un qui s'appelle ARK et l'autre BNF. C'est l'identifiant Ark qu'il faut retenir. On n'utilise pas l'autre.
2) L'identifiant ARK contient une URL complète : `https://catalogue.bnf.fr/ark:/12148/cb16180961h`. 

**EDIT :**

> Documentation Ark sur le site de la Bnf (https://www.bnf.fr/fr/lidentifiant-ark-archival-resource-key).
> 
> Le nom ARK est composé de lettres de l’alphabet ASCII, chiffres et éventuellement caractères spécifiques (« = », « * », etc.) à l’exception des caractères réservés suivants : « . », « / », « % » et « - ».
> 
> Dans l’exemple que je vous avait donné (https://catalogue.bnf.fr/ark:/12148/cb16180961h), le nom ark est cb16180961h
> 
> - cb est un préfixe qui sera toujours identique car il correspond à une entité nommante particulière ;
> - il est suivi d’une chaîne de 8 caractères (celle qui nous intéresse) mais je ne suis pas sûr qu’elle soit toujours composée uniquement d’éléments numériques ;
> - Le nom est terminé par un caractère de contrôle (ici « h ») qui n’est pas nécessairement une lettre. Je viens de tomber sur une caractère de contrôle qui est un élément numérique.
> 
> Les éléments fixes sont donc les lettres « cb » suivies d’une chaîne de 8 caractères ASCII.

Donc : `(?<=\/cb)[^\/%.-]{8}(?=.?$)`

**Todo :**

* [x] Ajouter ces champs dans le ME
* [x] Les prendre en charge dans la maquette et afficher les icônes
* [ ] Ajouter les variables de traduction
* [x] Importer un document test
* [ ] Écrire les CSS correspondants
